import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <div className="w-full flex justify-center item-center gap-5 py-2 shadow-sm shadow-gray-500 bg-gray-950">

          <div className="h-max w-1/2 flex">
            <input type="text" className="border border-gray-500 w-full p-2 text-gray-300" placeholder="Search item..." />
            <button className="p-2 bg-amber-800 border border-amber-800 text-white">🔍</button>
          </div>
        </div>

        <div className="p-5">
          {children}
        </div>

      </body>
    </html>
  );
}
